import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#080b10] text-[#e8edf3]">
      <Navbar />
      
      <main className="max-w-3xl mx-auto py-32 px-6">
        <h1 className="font-display font-bold text-4xl mb-2">Terms of Service</h1>
        <p className="text-[#6b7a8d] font-mono text-sm mb-12">Last updated: March 2025</p>

        <div className="space-y-12 font-mono">
          <section>
            <h2 className="text-xl font-display font-bold mb-4 text-[#00e5a0]">1. Acceptance of Terms</h2>
            <div className="space-y-4 text-[#e8edf3]/80 leading-relaxed text-sm">
              <p>By accessing and using CodeSense AI, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the service.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-display font-bold mb-4 text-[#00e5a0]">2. Use of Service</h2>
            <div className="space-y-4 text-[#e8edf3]/80 leading-relaxed text-sm">
              <p>CodeSense AI is designed to analyze and chat with GitHub repositories. When using our service, you agree to:</p>
              <ul className="list-disc pl-5 space-y-2">
                <li>Submit only public GitHub repository URLs that you have the right to access.</li>
                <li>Not use the service for any malicious or illegal activities.</li>
                <li>Not attempt to reverse engineer, disrupt, or gain unauthorized access to our infrastructure.</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-display font-bold mb-4 text-[#00e5a0]">3. Intellectual Property</h2>
            <div className="space-y-4 text-[#e8edf3]/80 leading-relaxed text-sm">
              <p>CodeSense AI and its original content, features, and functionality are owned by Jatin Dongre and are protected by international copyright, trademark, and other intellectual property laws.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-display font-bold mb-4 text-[#00e5a0]">4. AI Generated Content Disclaimer</h2>
            <div className="space-y-4 text-[#e8edf3]/80 leading-relaxed text-sm">
              <p>All analysis, responses, and reviews provided by CodeSense AI are generated by AI models. Please note:</p>
              <ul className="list-disc pl-5 space-y-2">
                <li>AI results are suggestions and should be verified by a human developer.</li>
                <li>We do not guarantee the accuracy, completeness, or reliability of AI-generated content.</li>
                <li>We are not responsible for any issues or damages arising from the use of AI suggestions.</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-display font-bold mb-4 text-[#00e5a0]">5. Limitations of Liability</h2>
            <div className="space-y-4 text-[#e8edf3]/80 leading-relaxed text-sm">
              <p>CodeSense AI is provided "as is" without any warranties. In no event shall we be liable for any indirect, incidental, special, or consequential damages resulting from your use of the service.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-display font-bold mb-4 text-[#00e5a0]">6. Changes to Terms</h2>
            <div className="space-y-4 text-[#e8edf3]/80 leading-relaxed text-sm">
              <p>We reserve the right to modify these Terms of Service at any time. We will notify you of any changes by posting the new terms on this page and updating the "Last updated" date.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-display font-bold mb-4 text-[#00e5a0]">7. Contact</h2>
            <div className="space-y-4 text-[#e8edf3]/80 leading-relaxed text-sm">
              <p>If you have any questions about these Terms, please contact us at support@codesenseai.com or through our <a href="/contact" className="text-[#00e5a0] hover:underline">Contact Page</a>.</p>
            </div>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  )
}
